### ISSUE TITLE
Question about the OS-SAR benchmark

### ISSUE THREAD

**Issue by Necolizer** [KPeng9510/OS-SAR#3]
Hi, I'm interested in your excellent work on OS-SAR. Thanks for your effort to make this benchmark open-source!

I'd like to ask one question confusing me. Your paper says that this OS-SAR benchmark features 3 datasets, 7 open-set recognition baselines and 3 backbones. But I find that this repository contains only dataloaders for NTU datasets, code of your proposed CrossMMD and the backbone CTR-GCN. I wonder whether I ignore some important scripts, just in a quick glance at this repo. If not, would you mind disclosing your plan to release the full OS-SAR benchmark? 

I'd be greateful if you could help me with this. Thanks in advance.

**Comment by KPeng9510** [comment]
Hi, thank you for your interests on our work. Please refer to the supplementary materials in our arxiv version paper for the data partition https://arxiv.org/pdf/2312.06330. We recorded every splits there. The dataloader can be easily reused for the NTU120 dataset and tyt dataset in case you format the data in the same way with the CTRGCN paper. Regarding the models, please replace the CTRGCN directly by HDGCN and Hyperformer according to their repos. https://github.com/ZhouYuxuanYX/Hyperformer and https://github.com/Jho-Yonsei/HD-GCN.

Thank you!

**Comment by Necolizer** [comment]
Thank you for your quick responses. Btw, it seems you mistakenly cite another Hyperformer (https://dl.acm.org/doi/10.1145/3539618.3591999) in your paper, instead of the actually-used one (https://github.com/ZhouYuxuanYX/Hyperformer) (https://arxiv.org/pdf/2211.09590). They are proposed by two distinct teams of researchers.

**Comment by KPeng9510** [comment]
Thank you for your nice finding! We will correct it in our journal extension.
